pub const INVALID_ACTION: felt252 =
    'BAD_PRIV_ESCROW_ACTION';

pub const INVALID_CALLDATA: felt252 =
    'BAD_PRIV_ESCROW_DATA';

pub const ZERO_CUSTODY_COMMITMENT: felt252 =
    'ZERO_CUSTODY_COMMIT';

pub const ZERO_RELEASE_COMMITMENT: felt252 =
    'ZERO_RELEASE_COMMIT';

pub const ZERO_REFUND_COMMITMENT: felt252 =
    'ZERO_REFUND_COMMIT';

pub const SAME_PATH_COMMITMENTS: felt252 =
    'SAME_PATH_COMMITMENTS';

pub const DUPLICATE_CUSTODY: felt252 =
    'CUSTODY_ALREADY_EXISTS';

pub const CUSTODY_NOT_FOUND: felt252 =
    'CUSTODY_NOT_FOUND';

pub const CUSTODY_CONSUMED: felt252 =
    'CUSTODY_ALREADY_CONSUMED';

pub const ZERO_SECRET: felt252 =
    'ZERO_ESCROW_SECRET';

pub const INVALID_REFUND_AFTER: felt252 =
    'BAD_REFUND_AFTER';

pub const RELEASE_WINDOW_CLOSED: felt252 =
    'RELEASE_WINDOW_CLOSED';

pub const REFUND_TOO_EARLY: felt252 =
    'REFUND_TOO_EARLY';

pub const RELEASE_SECRET_MISMATCH: felt252 =
    'BAD_RELEASE_SECRET';

pub const REFUND_SECRET_MISMATCH: felt252 =
    'BAD_REFUND_SECRET';

pub const FUNDS_NOT_RECEIVED: felt252 =
    'FUNDS_NOT_RECEIVED';

pub const APPROVAL_FAILED: felt252 =
    'APPROVAL_FAILED';

pub const APPROVAL_NOT_EXACT: felt252 =
    'APPROVAL_NOT_EXACT';

pub const STALE_ALLOWANCE: felt252 =
    'STALE_ALLOWANCE';

pub const RESERVE_INVARIANT: felt252 =
    'RESERVE_INVARIANT';
